### ISSUE TITLE
Missing use imports 

### ISSUE THREAD

**Issue by mngreece** [bigfork/silverstripe-oauth#11]
Missing references to Security and HTTP classes in the Controller. 

Currently throws an error.

See diff.

diff --git vendor/bigfork/silverstripe-oauth/src/Control/Controller.php vendor/bigfork/silverstripe-oauth/src/Control/Controller.php
index 25f4c07..5092f3f 100644
--- vendor/bigfork/silverstripe-oauth/src/Control/Controller.php
+++ vendor/bigfork/silverstripe-oauth/src/Control/Controller.php
@@ -8,10 +8,12 @@ use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
 use Psr\Log\LoggerInterface;
 use SilverStripe\Control\Controller as SilverStripeController;
 use SilverStripe\Control\Director;
+use SilverStripe\Control\HTTP;
 use SilverStripe\Control\HTTPRequest;
 use SilverStripe\Control\HTTPResponse;
 use SilverStripe\Control\HTTPResponse_Exception;
 use SilverStripe\Core\Injector\Injector;
+use SilverStripe\Security\Security;
 
 class Controller extends SilverStripeController
 {

**Comment by kinglozzer** [comment]
Thanks @mngreece, fixed and tagged in 2.0.1 :)
