### ISSUE TITLE
Mastodon OAuth has variable endpoints/clientId/SecretKey

### ISSUE THREAD

**Issue by Firesphere** [bigfork/silverstripe-oauth#15]
Mastodon OAuth works... ~ish.

It works out of the box just fine with `Lrf141\OAuth2\Client\Provider\Mastodon`, however, the Options for that provider, are variable.

If someone wants to log in with their Mastodon account, the instance is not at a given endpoint.

I'm on cloudisland.nz, whereas others are on mastodon.nz. I can create apps on-the-fly for a Mastodon instance I don't have app credentials for yet, but I'm not sure how I can inject them in to the whole process, so the provider gets the correct credentials...

Any idea/clue on where to look?

**Comment by Firesphere** [comment]
I'm thinking, I need to be able to at the moment of instantiation, see the request. If I can see what instance the user wants to log in with, I can pick-and-choose right there.

Does the provider get the request?

**Comment by Firesphere** [comment]
It will be different for each Instance.
Each user has to select their instance, and then, an app needs to be created and the user can log in.

Let me invite you to my stickertrade.me repo, so you can see how I hacked around it.

See the folder `oauth2-mastodon` in that repo, on how I hacked around it.

The resulting login screen ends up like you can see here: https://stickertrade.me/Security/login?BackURL=%2Fmy-account%2F

**Comment by kinglozzer** [comment]
Okay cool so it looks like you’ve managed to achieve it pretty well. I’m not sure there’s much we can really do in this module to help with Mastodon - it’s pretty unique with its “instances” thing, I’ve not encountered any other oauth providers that would need to add fields to the `LoginForm` like Mastodon does.

Maybe just some docs somewhere with an example if you’d be willing to PR that?
