### ISSUE TITLE
Need support for 2.x releases of oauth library

### ISSUE THREAD

**Issue by jam13** [bigfork/silverstripe-oauth#4]
Currently dependency is on 1.4 of league/oauth2-client, however a provider that I want to use (Keycloak) depends on 2.0.

New 2.x versions require PHP 5.6 which I assume is the reason for the bump. I've tested it with 2.2.1 and it seems to work ok so far. Any chance of upgrading?

**Comment by kinglozzer** [comment]
I don’t see any reason why not, I can tag the module in its current state as `1.0.0` and then the PHP 5.6+ version can be the `2.x` release line. Changes between the two `oauth2-client` versions look minimal

**Comment by jam13** [comment]
Thanks.

Noting the warning about not using this in production environments, is this just down to insufficient testing, or are there concerns about upstream code?

**Comment by kinglozzer** [comment]
> Noting the warning about not using this in production environments, is this just down to insufficient testing, or are there concerns about upstream code?

I mainly added that warning because I’ve not deployed this to any production environments yet, so it hasn’t undergone any “real world” user testing that I’m aware of

**Comment by kinglozzer** [comment]
I’ve released `1.0.0` of this module and the [oauth-login](https://github.com/bigfork/silverstripe-oauth-login) module, which now require `"league/oauth2-client": "^2"`
