### ISSUE TITLE
SilverStripe 4 support

### ISSUE THREAD

**Issue by Sil3ntStorm** [bigfork/silverstripe-oauth#5]
Do you have any plans on supporting this (and https://github.com/bigfork/silverstripe-oauth-login) for SilverStripe 4.x ?

**Comment by kinglozzer** [comment]
Absolutely! It’s a little hard to give an ETA as a lot of the authentication code has been rewritten for SS4 so I’m not really sure how much work it’ll be 😅

**Comment by kinglozzer** [comment]
This module is now SS4 compatible, https://github.com/bigfork/silverstripe-oauth-login still needs updating (https://github.com/bigfork/silverstripe-oauth-login/issues/11)
