### ISSUE TITLE
HTML code sent as plaintext when getAccessToken fails

### ISSUE THREAD

**Issue by Sil3ntStorm** [bigfork/silverstripe-oauth#9]
If [getAccessToken](https://github.com/bigfork/silverstripe-oauth/blob/master/src/Control/Controller.php#L139) throws [an Exception](https://github.com/thephpleague/oauth2-client/blob/master/src/Tool/RequiredParameterTrait.php#L35), somehow for some mysterious, magical reason SilverStripe decides to output a complete DOM tree [as plaintext](https://github.com/silverstripe/silverstripe-framework/blob/4.1/src/Control/HTTPResponse_Exception.php#L47). At that point in time it's still just the error message text, so through whatever zillion places it jumps afterwards a complete template HTML Dom gets added before the message.
Equally magically it doesn't seem to do that if I add a dummy 
```
try { 
    throw new BadMethodCallException('foo');
} catch (Exception $e) {
    $this->httpError(400, $e->getMessage());
}
```

in at the start of the callback function. Hence I'm creating this issue here, instead of over at silverstripe. 
Been trying to wrap my head around this for 4+ hours now, still no clue as to where the heck it decides to blow up, as SilverStripe is an unmaintainable messy jungle.

Using SS 4.1 with oauth and oauth-login 
New Base install of SS 4.1 with these two addons and a few Login providers.

**Comment by kinglozzer** [comment]
Are you seeing something like this?

<img width="1142" alt="screen shot 2018-05-01 at 15 13 50" src="https://user-images.githubusercontent.com/1655548/39475994-532d7dc8-4d52-11e8-898a-9b10ae5fadce.png">

I think what’s happening here is that the logging here is triggering output: https://github.com/bigfork/silverstripe-oauth/blob/master/src/Control/Controller.php#L165-L166. If I comment that logging out, I get the fully-rendered page as expected.

Not sure of the best way to approach logging here, I’ll look into it a bit more

**Comment by Sil3ntStorm** [comment]
I did get a full default page HTML source output as plaintext. Now (since I have been messing around, and reinstalling a bunch) I only get what looks like an error page HTML source.
Your picture looks like actual parsed HTML, that was sent with text/html Content-Type, or at least your browser renders it anyway.
I get something like this right now: 
![gh-bigfork-stripe-oauth-issue9](https://user-images.githubusercontent.com/12677273/39480904-f61a30d2-4d69-11e8-98a8-21443cb1cbe3.png)

But yes, you're right, if I comment out those two lines, then the HTML disappears and I end up with just the `Required parameter not passed: "code"`

**Comment by kinglozzer** [comment]
Okay, I think the best plan here is going to be to set up a custom logger which doesn’t trigger any HTTP output

**Comment by kinglozzer** [comment]
I’ve pushed up updated logging configuration which simply logs errors to PHP’s error log by default, plus an example for how to set up custom logging. Hopefully that’ll solve your issue!

I think you could now seeing just a plain error page because you don’t have an `ErrorPage` set up in the CMS with a 400 response code

**Comment by Sil3ntStorm** [comment]
This seems to be a general issue in SilverStripe though, doesn't it?  
As far as I can tell you were using the default SilverStripe logger before this change, and that somehow causes the Error Handling to be different if called, ultimately resulting in HTML being added before the error message from the Exception. The Exception itself will set the content-type header to text/plaintext which then causes conforming browsers to output the entire HTML as text.  
It seems to me that when (rightfully) setting the content type to text/plaintext for security reasons, no HTML should be added at all.

Anyway thanks for the quick fix :+1:

**Comment by kinglozzer** [comment]
Yeah the logging was outputting the `text/plain` content type, then `$this->httpError()` outputs HTML (assuming you’ve got an error page set up). Neither is aware of what the other is doing/has done, I think it’s just a quirk when using _both_ logging (which by default outputs errors) and trying to display a friendly error page.
